In [1]:
print("kalyan")

kalyan


In [4]:
def func(x):
    return x
func(2)


2

In [5]:
%config Completer.use_jedi = False


In [6]:
print("kalyan")

kalyan


In [7]:
pip install 'jupyter-ai>=1.0,<2.0'  # For JupyterLab 3
pip install jupyter-ai              # For JupyterLab 4




SyntaxError: invalid syntax (1191621912.py, line 1)

In [8]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.0 kB ? eta -:--:--
     -------------------- ------------------- 30.7/61.0 kB ? eta -:--:--
     -------------------------------------- 61.0/61.0 kB 461.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.5 MB 1.3 MB/s eta 0:00:12
   ---------------------------------------- 0.1/15.5 MB 762.6 kB/s eta 0:00:21
   ---------------------------------------- 0.1/15.5 MB 798.9 kB/s eta 0:00:20
   ---------------------------------------- 0.1/15.5 MB 798.9 kB/s eta 0:00:20
   ---------------------------------------- 0.1/15.5 MB 798.9 kB/s eta 0:00:20
    ---------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [9]:
import numpy

In [10]:
pip install pandas


Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB 1.3 MB/s eta 0:00:09
   ---------------------------------------- 0.1/11.5 MB 812.7 kB/s eta 0:00:15
   ---------------------------------------- 0.1/11.5 MB 751.6 kB/s eta 0:00:16
   ---------------------------------------- 0.1/11.5 MB 853.3 kB/s eta 0:00:14
    --------------------------------------- 0.2/11.5 MB 908.0 kB/s eta 0:00:13
    --------------------------------------- 0.2/11.5 MB 908.0 kB/s eta 0:00:13
    --------------------------------------- 0.3/11.5 MB 983.9 kB/s eta 0:00:12
   - -------------------------------------- 0.4/11.5 MB 1.0 MB/s eta 0:00:11
   - -------------------------------------- 0.4/11.5 MB 958.4 kB/s eta 0:00:12
   - -------------------------------------- 0.5/11.5 MB 1.0 MB/s eta 0:00:11
   - -------------------------------------- 0.5/11.5 MB 1.0 MB/s eta

In [2]:
print("kalyan")
#comments

kalyan
kalyan
kalyan
kalyan
kalyan
kalyan
kalyan
kalyan
kalyan
kalyan
kalyan


In [2]:
pip install ipykernel


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [ ]:
pip install tensorflow

In [8]:
#strings

a="kalyan"
print(a[0:len(a)],end=' ')
print(len(a))

kalyan 6


## lists

In [19]:
a=[1,2,3]
print("zeroth value : %d" % a[0]) 
print("length is: %d" % len(a))
a.append(4)
print(a)

zeroth value : 1
length is: 3
[1, 2, 3, 4]


In [27]:
#game of life python
import numpy as np

Z =np.array( [[0,0,0,0,0,0],
     [0,0,0,1,0,0],
     [0,1,0,1,0,0],
     [0,0,1,1,0,0],
     [0,0,0,0,0,0],
     [0,0,0,0,0,0]])

#broadcasting : adding a scalar to vector is known as broadcasting
print(Z+1)
print(Z.dtype)


[[1 1 1 1 1 1]
 [1 1 1 2 1 1]
 [1 2 1 2 1 1]
 [1 1 2 2 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
int32


In [2]:
import calendar
print(calendar.isleap(2024))

True


In [2]:
#handling exceptions
while True:
    try:
        x=int(input("enter the integer value"))
        print(x)
        break
    except ValueError:
        print("oops! print the integer value")
        

enter the integer value 2.3


oops! print the integer value


enter the integer value 1


1


In [10]:
import numpy as np
arr=np.array([1,2,3,4,5],dtype="float")
arr.dtype
arr

array([1., 2., 3., 4., 5.])

In [14]:
#multidimensional array declaration
#a=np.array([range(i,i+2) for i in [2,3,4]])
#a=np.array([[1,2,3],[4,5,6],[7,8,9]])

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
b=np.zeros(10,dtype=int)
b
c=np.ones((3,5) , dtype=float)
c
#for to fill with a unique value
c=np.full((3,5),3.14)
c

#for to create an array with the constriants like start= val,end= val and step
#we use arange function

d=np.arange(1,10,2)
d

np.linspace(1,2,5)


array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [26]:
#random function 
np.random.random((3,3))
np.random.normal(1,2,(3,3))

array([[-0.11476406, -1.7983164 , -1.04102243],
       [ 0.51419815, -0.69741805, -1.23025485],
       [-0.39126547,  0.4548198 ,  1.21225004]])

In [27]:
np.random.randint(1,10,(3,3))

array([[5, 4, 1],
       [7, 7, 8],
       [3, 7, 2]])

In [28]:
#eye() funcction to create an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
from  numpy import pi
import matplotlib.pyplot as plt
# x=np.linspace(1,2*pi,100)
# y=np.sin(x)
# plt.plot(y)
np.random.seed(0)
x1 = np.random.randint(10,size=4)
x2= np.random.randint(10,size = (3,3))
x3 = np.random.randint(10,size=(3,3,3))
x3
#every array has attributes ndim,size,shape
x3.shape
x3.size
x3.ndim
x3.nbytes

#reshaping the array

z=np.arange(1,10).reshape((3,3))
z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
import numpy as np
np.random.seed(0)

def reciprocal_values(n):
    output = np.empty(len(n))
    for i in range(len(n)):
        output[i] = 1/n[i]
    return output    
            
n=np.random.randint(1,10,size = 10)
reciprocal_values(n)
    
    

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ,
       0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [16]:
import pandas as pd
data = pd.Series([2.0,3,5,6,87,9])
print(data)
data.values
data.index
data[2:6]
#for to explicitly define the index
a=pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f'])
a

0     2.0
1     3.0
2     5.0
3     6.0
4    87.0
5     9.0
dtype: float64


a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [10]:
import pandas as p
import numpy as np




URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [1]:
pip3 install tensorflow

SyntaxError: invalid syntax (2357089093.py, line 1)

In [2]:
pip install tensorflow


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [1]:
import tensorflow as tf
